SET foreign_key_checks = 0;
truncate adminnotification_inbox;
truncate log_customer;
truncate log_quote;
truncate log_summary;
truncate log_summary_type;
truncate log_url;
truncate log_url_info;
truncate log_visitor;
truncate log_visitor_info;
truncate log_visitor_online;
truncate index_event;
truncate report_event;
truncate report_viewed_product_index;
truncate report_compared_product_index;
truncate catalog_compare_item;
truncate dataflow_batch_export;
truncate dataflow_batch_import;
truncate catalogindex_aggregation;
truncate catalogindex_aggregation_tag;
truncate catalogindex_aggregation_to_tag;
truncate aw_core_logger;
SET foreign_key_checks = 1;